from __future__ import annotations

import importlib.metadata
from typing import Any

import typer

helptext = """
Send Bark notifications from agent lifecycle hooks and direct CLI requests.

Install plugins:
  bark-agent-hook install
  bark-agent-hook install --agent codex
  bark-agent-hook install --agent claude --agent openclaw

Uninstall plugins:
  bark-agent-hook uninstall
  bark-agent-hook uninstall --agent codex

Direct Bark notification:
  bark-agent-hook send --title "Test" --body "Hello"
  bark-agent-hook send --device-key key1 --device-key key2 --body "Batch"

Hook commands used by the plugins:
  bark-agent-hook hook --runtime codex --event completion
  bark-agent-hook hook --runtime claude --event approval_needed --summary-mode extract
  bark-agent-hook hook --runtime claude --event attention_needed --summary-mode extract
  bark-agent-hook hook --runtime codex --event audit_only --summary-mode extract
  bark-agent-hook hook --runtime openclaw --event completion --summary-mode extract

Direct plugin install commands:
  codex plugin marketplace add qsoyq/bark-agent-hook
  codex plugin add bark-agent-hook-codex@bark-agent-hook
  claude plugin marketplace add qsoyq/bark-agent-hook
  claude plugin install bark-agent-hook@bark-agent-hook --scope user
  openclaw plugins install --link ./plugins/bark-agent-hook-openclaw
  openclaw plugins enable bark-agent-hook-openclaw

Configuration:
  For hook, BARK_DEVICE_KEY is required. Missing or empty means skip and exit 0.
  For send, BARK_DEVICE_KEY, BARK_DEVICE_KEYS, or --device-key is required. Missing values fail the command.
  BARK_DEVICE_KEYS is comma-separated and only used by send.
  BARK_GROUP is optional. For hook, it overrides the computed Bark group and may be a fixed value or template. For send, it is used literally.
  BARK_SERVER defaults to https://api.day.app.
  BARK_LEVEL, BARK_URL, BARK_EXTRA_PARAMS, BARK_DRY_RUN, and BARK_TIMEOUT are used by send.
  AGENT_BARK_NOTIFY_HOOK_URL optionally sets a Bark click URL template.
  AGENT_BARK_NOTIFY_TITLE_TEMPLATE optionally sets a notification title template.
  AGENT_BARK_NOTIFY_GROUP_MODE selects the computed group when BARK_GROUP is unset: agent, project, or project-branch.
  AGENT_BARK_NOTIFY_AUDIT_LOG=1 enables local JSONL audit logging.
  AGENT_BARK_NOTIFY_AUDIT_LOG_FILE overrides the audit log path.

Template variables:
  AGENT_BARK_NOTIFY_TITLE_TEMPLATE supports:
    {agent}, {event}, {project}, {branch}, {session}, {runtime}, {cwd_basename},
    {LODY_ELECTRON_BOOTSTRAP}, {LODY_ELECTRON_SESSION_USER_ID}, {LODY_SESSION_ID},
    {LODY_WORKSPACE_SESSION_ID}.
    Example: AGENT_BARK_NOTIFY_TITLE_TEMPLATE='[{agent}][{event}][{LODY_SESSION_ID}]'
  BARK_GROUP supports:
    {agent}, {event}, {project}, {branch}, {session}, {runtime}, {cwd_basename},
    {LODY_ELECTRON_BOOTSTRAP}, {LODY_ELECTRON_SESSION_USER_ID}, {LODY_SESSION_ID},
    {LODY_WORKSPACE_SESSION_ID}.
    Example: BARK_GROUP='{project}@{branch}'
  AGENT_BARK_NOTIFY_HOOK_URL supports:
    {runtime}, {agent}, {event}, {project}, {branch}, {session}, {session_id},
    {session_key}, {conversation_id}, {message_id}, {run_id}, {agent_id},
    {workspace_dir}, {cwd_basename}, {LODY_ELECTRON_BOOTSTRAP},
    {LODY_ELECTRON_SESSION_USER_ID}, {LODY_SESSION_ID}, {LODY_WORKSPACE_SESSION_ID}.
    Example: AGENT_BARK_NOTIFY_HOOK_URL='https://lody.ai/users/{LODY_ELECTRON_SESSION_USER_ID}/sessions/{LODY_SESSION_ID}'
  Hook URL variable values are percent-encoded; title and group variables are not URL-encoded.
  Lody passthrough variables are read from LodySettings and limited to the four LODY_* keys above.

Audit log field sources:
  Generated by the hook command:
    1. time: UTC timestamp when the audit record is created.
    2. status: final hook handling result, such as sent, logged_audit_only_event, skipped_duplicate, or skipped_missing_device_key.
    3. bark_agent_hook_version: installed bark-agent-hook package version, or null when package metadata is unavailable.
    4. command_dir: directory containing the invoked command resolved from sys.argv[0] or PATH, or null when unavailable.
  CLI options:
    1. runtime: agent runtime selected by --runtime or auto detection.
    2. event: notification event selected by --event or inferred from the payload.
    3. summary_mode: notification body mode selected by --summary-mode.
  Hook payload-derived values:
    1. hook_event_name: hook event name read from hook_event_name, event, event_name, or type.
    2. project: project name derived from payload metadata or the current working directory.
    3. session_id_hash: hashed session identifier; raw session IDs are not logged.
  Built notification-derived values:
    1. dedupe_key_hash: hashed notification dedupe key.
    2. title: final notification title.
    3. body_len: length of the final notification body; notification bodies are not logged.
  Lody environment passthrough:
    1. lody: non-empty whitelisted Lody environment values managed by LodySettings.
       Keys: LODY_ELECTRON_BOOTSTRAP, LODY_ELECTRON_SESSION_USER_ID,
       LODY_SESSION_ID, and LODY_WORKSPACE_SESSION_ID.
"""


def version_callback(ctx: typer.Context, value: bool) -> None:
    if not value:
        return
    name = ctx.find_root().info_name or "bark-agent-hook"
    version = importlib.metadata.version("bark-agent-hook")
    typer.echo(f"{name} cli version: {version}")
    raise typer.Exit(0)


def default_invoke_without_command(
    _: bool = typer.Option(False, "--version", "-v", "-V", callback=version_callback),
) -> None:
    return None


def make_typer(help: str, **kwargs: Any) -> typer.Typer:
    app = typer.Typer(help=help, **kwargs)
    app.callback(invoke_without_command=True)(default_invoke_without_command)
    return app


cmd = make_typer(helptext)
