import hashlib
import importlib.metadata
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Literal, TypeGuard
from urllib.parse import quote, urlsplit, urlunsplit

import httpx
import typer
from rich.console import Console
from rich.table import Table

from bark_agent_hook.settings import LodySettings

helptext = """
Send Bark notifications from agent lifecycle hooks.

Install plugins:
  bark-agent-hook install
  bark-agent-hook install --agent codex
  bark-agent-hook install --agent claude --agent openclaw

Uninstall plugins:
  bark-agent-hook uninstall
  bark-agent-hook uninstall --agent codex

Hook commands used by the plugins:
  bark-agent-hook hook --runtime codex --event completion
  bark-agent-hook hook --runtime claude --event approval_needed --summary-mode extract
  bark-agent-hook hook --runtime openclaw --event completion --summary-mode extract

Direct plugin install commands:
  codex plugin marketplace add qsoyq/bark-agent-hook
  codex plugin add bark-agent-hook-codex@bark-agent-hook
  claude plugin marketplace add qsoyq/bark-agent-hook
  claude plugin install bark-agent-hook@bark-agent-hook --scope user
  openclaw plugins install --link ./plugins/bark-agent-hook-openclaw
  openclaw plugins enable bark-agent-hook-openclaw

Configuration:
  BARK_DEVICE_KEY is required. Missing or empty means skip and exit 0.
  BARK_GROUP is optional and overrides the computed Bark group.
  BARK_SERVER defaults to https://api.day.app.
  AGENT_BARK_NOTIFY_HOOK_URL optionally sets a Bark click URL template.
  AGENT_BARK_NOTIFY_TITLE_TEMPLATE optionally sets a notification title template.
  AGENT_BARK_NOTIFY_GROUP_MODE selects the computed group when BARK_GROUP is unset: agent, project, or project-branch.
  AGENT_BARK_NOTIFY_AUDIT_LOG=1 enables local JSONL audit logging.
  AGENT_BARK_NOTIFY_AUDIT_LOG_FILE overrides the audit log path.

Template variables:
  AGENT_BARK_NOTIFY_TITLE_TEMPLATE supports:
    {agent}, {event}, {project}, {branch}, {session}, {runtime}, {cwd_basename},
    {LODY_ELECTRON_BOOTSTRAP}, {LODY_ELECTRON_SESSION_USER_ID}, {LODY_SESSION_ID},
    {LODY_WORKSPACE_SESSION_ID}.
    Example: AGENT_BARK_NOTIFY_TITLE_TEMPLATE='[{agent}][{event}][{LODY_SESSION_ID}]'
  AGENT_BARK_NOTIFY_HOOK_URL supports:
    {runtime}, {agent}, {event}, {project}, {branch}, {session}, {session_id},
    {session_key}, {conversation_id}, {message_id}, {run_id}, {agent_id},
    {workspace_dir}, {cwd_basename}, {LODY_ELECTRON_BOOTSTRAP},
    {LODY_ELECTRON_SESSION_USER_ID}, {LODY_SESSION_ID}, {LODY_WORKSPACE_SESSION_ID}.
    Example: AGENT_BARK_NOTIFY_HOOK_URL='https://lody.ai/users/{LODY_ELECTRON_SESSION_USER_ID}/sessions/{LODY_SESSION_ID}'
  Hook URL variable values are percent-encoded; title variables are not URL-encoded.
  Lody passthrough variables are read from LodySettings and limited to the four LODY_* keys above.

Audit log field sources:
  Generated by the hook command:
    1. time: UTC timestamp when the audit record is created.
    2. status: final hook handling result, such as sent, skipped_duplicate, or skipped_missing_device_key.
  CLI options:
    1. runtime: agent runtime selected by --runtime or auto detection.
    2. event: notification event selected by --event or inferred from the payload.
    3. summary_mode: notification body mode selected by --summary-mode.
  Hook payload-derived values:
    1. hook_event_name: hook event name read from hook_event_name, event, event_name, or type.
    2. project: project name derived from payload metadata or the current working directory.
    3. session_id_hash: hashed session identifier; raw session IDs are not logged.
  Built notification-derived values:
    1. dedupe_key_hash: hashed notification dedupe key.
    2. title: final notification title.
    3. body_len: length of the final notification body; notification bodies are not logged.
  Lody environment passthrough:
    1. lody: non-empty whitelisted Lody environment values managed by LodySettings.
       Keys: LODY_ELECTRON_BOOTSTRAP, LODY_ELECTRON_SESSION_USER_ID,
       LODY_SESSION_ID, and LODY_WORKSPACE_SESSION_ID.
"""


def version_callback(ctx: typer.Context, value: bool) -> None:
    if not value:
        return
    name = ctx.find_root().info_name or "bark-agent-hook"
    version = importlib.metadata.version("bark-agent-hook")
    typer.echo(f"{name} cli version: {version}")
    raise typer.Exit(0)


def default_invoke_without_command(
    _: bool = typer.Option(False, "--version", "-v", "-V", callback=version_callback),
) -> None:
    return None


def make_typer(help: str, **kwargs: Any) -> typer.Typer:
    app = typer.Typer(help=help, **kwargs)
    app.callback(invoke_without_command=True)(default_invoke_without_command)
    return app


cmd = make_typer(helptext)

Runtime = Literal["auto", "codex", "claude", "openclaw"]
Event = Literal["auto", "completion", "approval_needed", "failed"]
SummaryMode = Literal["fixed", "extract"]
GroupMode = Literal["agent", "project", "project-branch"]
InstallStatus = Literal["installed", "updated", "downgraded", "unchanged", "removed", "failed", "skipped"]


class GroupModeOption(str, Enum):
    agent = "agent"
    project = "project"
    project_branch = "project-branch"


class AgentOption(str, Enum):
    codex = "codex"
    claude = "claude"
    openclaw = "openclaw"


CODEX_ICON_URL = "https://raw.githubusercontent.com/lobehub/lobe-icons/refs/heads/master/packages/static-png/light/codex-color.png"
CLAUDE_CODE_ICON_URL = "https://raw.githubusercontent.com/lobehub/lobe-icons/refs/heads/master/packages/static-png/light/claudecode-color.png"
OPENCLAW_ICON_URL = "https://openclaw.ai/apple-touch-icon.png"
LODY_ICON_URL = "https://lody.ai/favicon.ico"

DEFAULT_MESSAGES: dict[str, str] = {
    "completion": "任务已完成",
    "approval_needed": "需要你审批当前操作",
    "failed": "本轮因错误停止",
}
EVENT_LABELS: dict[str, str] = {
    "completion": "Done",
    "approval_needed": "Approval",
    "failed": "Failed",
}

MAX_MESSAGE_LENGTH = 80
DEFAULT_SUMMARY_MAX_CHARS = 120
MAX_TRANSCRIPT_BYTES = 1024 * 1024
DEDUP_TTL_SECONDS = 60 * 60
HOOK_URL_TEMPLATE_ENV = "AGENT_BARK_NOTIFY_HOOK_URL"
TITLE_TEMPLATE_ENV = "AGENT_BARK_NOTIFY_TITLE_TEMPLATE"
DEFAULT_TITLE_TEMPLATE = "[{agent}][{event}][{project}][{branch}][{session}]"
GROUP_MODE_ENV = "AGENT_BARK_NOTIFY_GROUP_MODE"
GROUP_MODE_CHOICES: tuple[GroupMode, ...] = ("agent", "project", "project-branch")
AUDIT_LOG_ENV = "AGENT_BARK_NOTIFY_AUDIT_LOG"
AUDIT_LOG_FILE_ENV = "AGENT_BARK_NOTIFY_AUDIT_LOG_FILE"
DEFAULT_AUDIT_LOG_PATH = Path("~/.bark-agent-hook/bark-agent-hook.log")
SENSITIVE_KEY_RE = re.compile(r"(?i)\b(authorization|cookie|set-cookie|x-api-key|api[_-]?key|token|secret|password|passwd|bearer)\b")
SENSITIVE_ASSIGNMENT_RE = re.compile(r"(?i)\b([a-z0-9_.-]*(?:token|secret|password|passwd|cookie|authorization|api[_-]?key)[a-z0-9_.-]*)\s*[:=]\s*('[^']*'|\"[^\"]*\"|[^\s,;]+)")
BEARER_RE = re.compile(r"(?i)\bbearer\s+[a-z0-9._~+/=-]+")
FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)
SHELL_PREFIX_RE = re.compile(r"^\s*(?:bash|zsh|sh|fish|python|python3|node|npm|pnpm|yarn|curl|ssh|scp|rsync)\b", re.IGNORECASE)
OPENCLAW_CONVERSATION_ACCESS_PATCH = '{"plugins":{"entries":{"bark-agent-hook-openclaw":{"hooks":{"allowConversationAccess":true}}}}}'


@dataclass(frozen=True)
class CommandResult:
    args: list[str]
    returncode: int
    stdout: str
    stderr: str


@dataclass(frozen=True)
class InstallResult:
    agent: str
    status: InstallStatus
    before_version: str | None
    after_version: str | None
    cli_path: str | None
    note: str
    failed_command: list[str] | None = None


@dataclass(frozen=True)
class AgentIdentity:
    name: str
    icon_url: str


@dataclass(frozen=True)
class Notification:
    title: str
    body: str
    icon_url: str
    group: str | None
    bark_url: str
    click_url: str | None
    dedupe_key: str


def _read_stdin() -> str:
    try:
        return typer.get_text_stream("stdin").read()
    except OSError:
        return ""


def parse_hook_payload(raw: str) -> dict[str, Any]:
    if not raw.strip():
        return {}
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def detect_identity(env: dict[str, str], lody_settings: LodySettings) -> AgentIdentity:
    if lody_settings.has_lody_signal() or env.get("__CFBundleIdentifier") == "ai.lody.desktop":
        return AgentIdentity("Lody", LODY_ICON_URL)
    if env.get("CLAUDECODE") or env.get("CLAUDE_CODE") or env.get("CLAUDE_PROJECT_DIR") or env.get("CLAUDE_CONFIG_DIR"):
        return AgentIdentity("Claude Code", CLAUDE_CODE_ICON_URL)
    return AgentIdentity("Codex", CODEX_ICON_URL)


def identity_for_runtime(runtime: str, env: dict[str, str], lody_settings: LodySettings) -> AgentIdentity:
    if runtime == "openclaw":
        return AgentIdentity("OpenClaw", OPENCLAW_ICON_URL)
    if runtime == "claude":
        return AgentIdentity("Claude Code", CLAUDE_CODE_ICON_URL)
    if runtime == "codex":
        return AgentIdentity("Codex", CODEX_ICON_URL)
    return detect_identity(env, lody_settings)


def detect_runtime(runtime: Runtime, env: dict[str, str], payload: dict[str, Any], lody_settings: LodySettings) -> str:
    if runtime != "auto":
        return runtime
    if lody_settings.has_lody_signal() or env.get("__CFBundleIdentifier") == "ai.lody.desktop":
        return "lody"
    if env.get("CLAUDECODE") or env.get("CLAUDE_CODE") or env.get("CLAUDE_PROJECT_DIR") or env.get("CLAUDE_CONFIG_DIR"):
        return "claude"
    if env.get("OPENCLAW_SESSION_ID") or env.get("OPENCLAW_WORKSPACE_DIR") or env.get("OPENCLAW_GATEWAY_PORT"):
        return "openclaw"
    if env.get("CODEX_CI") or env.get("CODEX_THREAD_ID"):
        return "codex"
    payload_hint = f"{payload.get('runtime') or ''} {payload.get('source') or ''}".lower()
    if "claude" in payload_hint:
        return "claude"
    if "codex" in payload_hint:
        return "codex"
    if "openclaw" in payload_hint:
        return "openclaw"
    return "codex"


def detect_event(event: Event, payload: dict[str, Any]) -> str | None:
    if event != "auto":
        return event

    hook_event = str(payload.get("hook_event_name") or payload.get("event") or payload.get("event_name") or payload.get("type") or "")
    if hook_event in {"PermissionRequest", "approval_needed", "approval-needed", "approval:needed", "before_tool_call"}:
        return "approval_needed"
    if hook_event in {"agent_end", "agent:end"}:
        return "completion" if payload.get("success") is not False else "failed"
    if hook_event in {"message_sent", "message:sent"}:
        return "completion" if payload.get("success") is not False else "failed"
    if hook_event == "Notification":
        message = str(payload.get("message") or payload.get("notification_type") or payload.get("reason") or "")
        if "permission" in message.lower() or "approval" in message.lower():
            return "approval_needed"
        return None
    if hook_event == "Stop":
        return "completion"
    if hook_event in {"StopFailure", "SessionEnd"} and str(payload.get("reason") or payload.get("status") or "").lower() in {"failed", "error"}:
        return "failed"
    return None


def project_name(payload: dict[str, Any], cwd: Path | None = None) -> str:
    for key in ("project_name", "workspace_name", "repository", "repo", "agentId", "agent_id", "name"):
        raw_name = payload.get(key)
        if isinstance(raw_name, str) and raw_name.strip():
            return raw_name.strip()

    env = os.environ
    for key in ("AGENT_BARK_NOTIFY_PROJECT_NAME", "OPENCLAW_WORKSPACE_NAME", "CODEX_WORKSPACE_NAME", "CODEX_PROJECT_NAME", "LODY_WORKSPACE_NAME", "LODY_PROJECT_NAME"):
        raw_name = env.get(key)
        if raw_name and raw_name.strip():
            return raw_name.strip()

    raw = payload.get("cwd") or payload.get("workspace") or payload.get("workspaceDir") or payload.get("project_path")
    if isinstance(raw, str) and raw:
        return Path(raw).name
    return (cwd or Path.cwd()).name


def _path_from_payload(payload: dict[str, Any], cwd: Path | None = None) -> Path:
    for key in ("cwd", "workspace", "workspaceDir", "workspace_dir", "project_path"):
        raw = payload.get(key)
        if isinstance(raw, str) and raw:
            return Path(raw)
    return cwd or Path.cwd()


def cwd_basename(payload: dict[str, Any], cwd: Path | None = None) -> str:
    return _path_from_payload(payload, cwd).name


def branch_name(payload: dict[str, Any], env: dict[str, str], cwd: Path | None = None) -> str:
    for key in ("branch_name", "branch", "git_branch", "ref_name"):
        raw_name = payload.get(key)
        if isinstance(raw_name, str) and raw_name.strip():
            return raw_name.strip().removeprefix("refs/heads/")

    for key in ("AGENT_BARK_NOTIFY_BRANCH_NAME", "CODEX_BRANCH_NAME", "GIT_BRANCH", "BRANCH_NAME"):
        raw_name = env.get(key)
        if raw_name and raw_name.strip():
            return raw_name.strip().removeprefix("refs/heads/")

    repo_path = _path_from_payload(payload, cwd)
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "branch", "--show-current"],
            check=False,
            capture_output=True,
            text=True,
            timeout=1,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    if result.returncode != 0:
        return ""
    return result.stdout.strip()


def _explicit_project_name(payload: dict[str, Any], env: dict[str, str], *, include_agent_id: bool) -> str:
    keys = ["project_name", "workspace_name", "repository", "repo"]
    if include_agent_id:
        keys.extend(["agentId", "agent_id", "name"])
    for key in keys:
        raw_name = payload.get(key)
        if isinstance(raw_name, str) and raw_name.strip():
            return raw_name.strip()

    env_keys = [
        "AGENT_BARK_NOTIFY_PROJECT_NAME",
        "OPENCLAW_WORKSPACE_NAME",
        "CODEX_WORKSPACE_NAME",
        "CODEX_PROJECT_NAME",
        "LODY_WORKSPACE_NAME",
        "LODY_PROJECT_NAME",
    ]
    for key in env_keys:
        raw_name = env.get(key)
        if raw_name and raw_name.strip():
            return raw_name.strip()
    return ""


def title_project_name(runtime: str, payload: dict[str, Any], env: dict[str, str], cwd: Path | None = None) -> str:
    if runtime == "openclaw":
        return _explicit_project_name(payload, env, include_agent_id=False)
    return project_name(payload, cwd)


def title_branch_name(runtime: str, payload: dict[str, Any], env: dict[str, str], cwd: Path | None = None) -> str:
    if runtime != "openclaw":
        return branch_name(payload, env, cwd)

    for key in ("branch_name", "branch", "git_branch", "ref_name"):
        raw_name = payload.get(key)
        if isinstance(raw_name, str) and raw_name.strip():
            return raw_name.strip().removeprefix("refs/heads/")

    for key in ("AGENT_BARK_NOTIFY_BRANCH_NAME", "CODEX_BRANCH_NAME", "GIT_BRANCH", "BRANCH_NAME"):
        raw_name = env.get(key)
        if raw_name and raw_name.strip():
            return raw_name.strip().removeprefix("refs/heads/")
    return ""


def session_name(payload: dict[str, Any], env: dict[str, str]) -> str:
    for key in ("session_name", "conversation_name", "thread_name", "workspace_session_name"):
        raw_name = payload.get(key)
        if isinstance(raw_name, str) and raw_name.strip():
            return raw_name.strip()

    for key in ("AGENT_BARK_NOTIFY_SESSION_NAME", "OPENCLAW_SESSION_NAME", "CODEX_SESSION_NAME", "LODY_SESSION_NAME"):
        raw_name = env.get(key)
        if raw_name and raw_name.strip():
            return raw_name.strip()
    return ""


def safe_message(event: str, message: str | None) -> str:
    body = (message or DEFAULT_MESSAGES.get(event) or "任务状态已更新").strip()
    body = body.replace("\n", " ")
    if len(body) > MAX_MESSAGE_LENGTH:
        return f"{body[: MAX_MESSAGE_LENGTH - 1]}…"
    return body


def event_label(event: str) -> str:
    return EVENT_LABELS.get(event, "Update")


class _SafeTitleVars(dict[str, str]):
    def __missing__(self, key: str) -> str:
        return "{" + key + "}"


def _default_title(values: dict[str, str]) -> str:
    parts = [values[key] for key in ("agent", "event", "project", "branch", "session") if values.get(key)]
    return "".join(f"[{part}]" for part in parts)


def notification_title(*, runtime: str, identity: AgentIdentity, event: str, payload: dict[str, Any], env: dict[str, str], lody_settings: LodySettings, cwd: Path | None = None) -> str:
    values = _SafeTitleVars(
        agent=identity.name,
        event=event_label(event),
        project=title_project_name(runtime, payload, env, cwd),
        runtime=runtime,
        cwd_basename=cwd_basename(payload, cwd),
        branch=title_branch_name(runtime, payload, env, cwd),
        session=session_name(payload, env),
    )
    values.update(lody_settings.template_values())
    configured_template = env.get(TITLE_TEMPLATE_ENV, "").strip()
    if not configured_template:
        title = _default_title(values)
        return title or _default_title(_SafeTitleVars(agent=identity.name, event=event_label(event)))
    try:
        title = configured_template.format_map(values)
    except ValueError:
        title = _default_title(values)
    return " ".join(title.split()) or _default_title(values)


def _payload_value(payload: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = payload.get(key)
        if value is None or isinstance(value, dict | list):
            continue
        text = str(value).strip()
        if text:
            return text
    return ""


def _encoded_hook_url_vars(
    *,
    runtime: str,
    identity: AgentIdentity,
    event: str,
    payload: dict[str, Any],
    env: dict[str, str],
    lody_settings: LodySettings,
    cwd: Path | None = None,
) -> dict[str, str]:
    values = {
        "runtime": runtime,
        "agent": identity.name,
        "event": event,
        "project": project_name(payload, cwd),
        "branch": branch_name(payload, env, cwd),
        "session": session_name(payload, env),
        "session_id": _payload_value(payload, "session_id", "sessionId"),
        "session_key": _payload_value(payload, "session_key", "sessionKey"),
        "conversation_id": _payload_value(payload, "conversation_id", "conversationId"),
        "message_id": _payload_value(payload, "message_id", "messageId"),
        "run_id": _payload_value(payload, "run_id", "runId"),
        "agent_id": _payload_value(payload, "agent_id", "agentId"),
        "workspace_dir": _payload_value(payload, "workspace_dir", "workspaceDir", "workspace", "cwd", "project_path"),
        "cwd_basename": cwd_basename(payload, cwd),
    }
    values.update(lody_settings.template_values())
    return {key: quote(value, safe="") for key, value in values.items()}


def hook_click_url(
    *,
    runtime: str,
    identity: AgentIdentity,
    event: str,
    payload: dict[str, Any],
    env: dict[str, str],
    lody_settings: LodySettings,
    cwd: Path | None = None,
) -> str | None:
    configured_template = _env_value(env, HOOK_URL_TEMPLATE_ENV)
    if not configured_template:
        return None
    try:
        rendered = configured_template.format_map(_encoded_hook_url_vars(runtime=runtime, identity=identity, event=event, payload=payload, env=env, lody_settings=lody_settings, cwd=cwd))
    except (KeyError, ValueError):
        return None
    rendered = rendered.strip()
    return rendered or None


def _strip_url_query(value: str) -> str:
    def replace(match: re.Match[str]) -> str:
        raw_url = match.group(0)
        split = urlsplit(raw_url)
        return urlunsplit((split.scheme, split.netloc, split.path, "", split.fragment))

    return re.sub(r"https?://[^\s<>'\")]+", replace, value)


def _redact_url(value: str) -> str:
    def replace(match: re.Match[str]) -> str:
        raw_url = match.group(0)
        split = urlsplit(raw_url)
        return urlunsplit((split.scheme, split.netloc, "/[REDACTED]", "", ""))

    return re.sub(r"https?://[^\s<>'\")]+", replace, value)


def _extract_text(value: Any) -> str | None:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        parts = [_extract_text(item) for item in value]
        return " ".join(part for part in parts if part)
    if isinstance(value, dict):
        for key in ("text", "content", "message"):
            text = _extract_text(value.get(key))
            if text:
                return text
    return None


def _extract_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _looks_like_raw_json(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return True
    if (stripped.startswith("{") and stripped.endswith("}")) or (stripped.startswith("[") and stripped.endswith("]")):
        return True
    return stripped.count('":') >= 3 and stripped.count("{") + stripped.count("[") >= 1


def _truncate_summary(text: str, max_chars: int) -> str:
    limit = max(1, max_chars)
    if len(text) <= limit:
        return text
    if limit == 1:
        return "…"
    return f"{text[: limit - 1].rstrip()}…"


def clean_summary_text(text: str | None, max_chars: int) -> str | None:
    if not text:
        return None
    body = FENCED_CODE_RE.sub(" ", text)
    body = BEARER_RE.sub("Bearer [REDACTED]", body)
    body = SENSITIVE_ASSIGNMENT_RE.sub(lambda m: f"{m.group(1)}=[REDACTED]", body)
    body = _strip_url_query(body)
    body = " ".join(body.split())
    body = body.strip("` \t\r\n")
    if not body or _looks_like_raw_json(body):
        return None
    if SENSITIVE_KEY_RE.search(body) and "[REDACTED]" not in body:
        return None
    return _truncate_summary(body, max_chars)


def _hash_value(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    if not text:
        return None
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def _hook_event_name(payload: dict[str, Any]) -> str | None:
    value = payload.get("hook_event_name") or payload.get("event") or payload.get("event_name") or payload.get("type")
    return str(value) if value is not None else None


def _env_value(env: dict[str, str], key: str, default: str = "") -> str:
    value = env.get(key, default).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1].strip()
    return value


def _is_group_mode(value: str) -> TypeGuard[GroupMode]:
    return value in GROUP_MODE_CHOICES


def _group_mode_error(value: str) -> typer.BadParameter:
    choices = ", ".join(GROUP_MODE_CHOICES)
    return typer.BadParameter(f"{GROUP_MODE_ENV} must be one of: {choices}; got {value!r}")


def resolve_group_mode(cli_group_mode: GroupModeOption | None, env: dict[str, str]) -> GroupMode:
    if cli_group_mode is not None:
        value = cli_group_mode.value
        if _is_group_mode(value):
            return value
        raise _group_mode_error(value)

    env_value = _env_value(env, GROUP_MODE_ENV)
    if not env_value:
        return "agent"
    if _is_group_mode(env_value):
        return env_value
    raise _group_mode_error(env_value)


def notification_group(
    *,
    identity: AgentIdentity,
    payload: dict[str, Any],
    env: dict[str, str],
    group_mode: GroupMode,
    cwd: Path | None = None,
) -> str | None:
    configured_group = _env_value(env, "BARK_GROUP")
    if configured_group:
        return configured_group

    if group_mode == "agent":
        return identity.name

    project = project_name(payload, cwd).strip()
    if group_mode == "project":
        return project or identity.name

    if not project:
        return identity.name
    branch = branch_name(payload, env, cwd).strip()
    if not branch:
        return project
    return f"{project}@{branch}"


def _session_id(payload: dict[str, Any]) -> str | None:
    value = payload.get("session_id") or payload.get("sessionId") or payload.get("sessionKey") or payload.get("conversation_id") or payload.get("transcript_path")
    return str(value) if value is not None else None


def _audit_enabled(env: dict[str, str]) -> bool:
    return _env_value(env, AUDIT_LOG_ENV).lower() in {"1", "true", "yes", "on"}


def _audit_log_path(env: dict[str, str]) -> Path:
    configured = _env_value(env, AUDIT_LOG_FILE_ENV)
    if configured:
        return Path(configured).expanduser()
    return DEFAULT_AUDIT_LOG_PATH.expanduser()


def _safe_error_message(error: BaseException) -> str:
    message = " ".join(str(error).split())
    message = BEARER_RE.sub("Bearer [REDACTED]", message)
    message = SENSITIVE_ASSIGNMENT_RE.sub(lambda m: f"{m.group(1)}=[REDACTED]", message)
    message = _redact_url(message)
    return _truncate_summary(message, 200)


def _write_audit_record(env: dict[str, str], record: dict[str, Any]) -> None:
    if not _audit_enabled(env):
        return
    try:
        path = _audit_log_path(env)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False, sort_keys=True))
            f.write("\n")
    except OSError:
        return


def _new_audit_record(
    *,
    runtime: str,
    event: str | None,
    payload: dict[str, Any],
    summary_mode: SummaryMode,
    lody_settings: LodySettings,
    cwd: Path | None = None,
) -> dict[str, Any]:
    record: dict[str, Any] = {
        "time": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "runtime": runtime,
        "event": event,
        "hook_event_name": _hook_event_name(payload),
        "status": None,
        "project": project_name(payload, cwd),
        "session_id_hash": _hash_value(_session_id(payload)),
        "dedupe_key_hash": None,
        "summary_mode": summary_mode,
        "title": None,
        "body_len": None,
    }
    lody_values = lody_settings.audit_values()
    if lody_values:
        record["lody"] = lody_values
    return record


def _finish_audit_record(
    env: dict[str, str],
    record: dict[str, Any],
    *,
    status: str,
    notification: Notification | None = None,
    error: BaseException | None = None,
) -> None:
    record["status"] = status
    if notification is not None:
        record["dedupe_key_hash"] = _hash_value(notification.dedupe_key)
        record["title"] = notification.title
        record["body_len"] = len(notification.body)
    if error is not None:
        record["error_class"] = error.__class__.__name__
        record["error_message"] = _safe_error_message(error)
    _write_audit_record(env, record)


def _assistant_text_from_transcript_item(item: dict[str, Any]) -> str | None:
    role = str(item.get("role") or "").lower()
    item_type = str(item.get("type") or "").lower()
    message = item.get("message")
    if isinstance(message, dict):
        role = str(message.get("role") or role).lower()
        if role == "assistant":
            return _extract_text(message.get("content"))
    if role == "assistant":
        return _extract_text(item.get("content") or item.get("text") or item.get("message"))
    if item_type in {"assistant", "final", "assistant_message"}:
        return _extract_text(item.get("content") or item.get("text") or item.get("message"))
    return None


def _read_transcript_messages(transcript_path: str | None) -> list[str]:
    if not transcript_path:
        return []
    path = Path(transcript_path)
    if not path.is_file():
        return []
    try:
        raw = path.read_bytes()[:MAX_TRANSCRIPT_BYTES].decode(errors="replace")
    except OSError:
        return []

    messages: list[str] = []
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        value = None
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                text = _assistant_text_from_transcript_item(item)
                if text:
                    messages.append(text)
        return messages
    if isinstance(value, dict):
        for key in ("messages", "items", "events"):
            nested = value.get(key)
            if isinstance(nested, list):
                for item in nested:
                    if isinstance(item, dict):
                        text = _assistant_text_from_transcript_item(item)
                        if text:
                            messages.append(text)
                return messages
        text = _assistant_text_from_transcript_item(value)
        return [text] if text else []

    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            item = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(item, dict):
            text = _assistant_text_from_transcript_item(item)
            if text:
                messages.append(text)
    return messages


def _safe_tool_detail(tool_input: dict[str, Any]) -> str | None:
    for key in ("path", "file_path", "file", "cwd", "workspace", "project_path"):
        value = tool_input.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    for key in ("command", "cmd"):
        value = tool_input.get(key)
        if not isinstance(value, str) or not value.strip():
            continue
        command = " ".join(value.split())
        if len(command) > 80 or SENSITIVE_KEY_RE.search(command):
            return None
        if SHELL_PREFIX_RE.search(command):
            return None
        return command
    return None


def _approval_tool_summary(tool_name: str | None, detail: str | None, max_chars: int) -> str | None:
    if not tool_name and not detail:
        return None
    if tool_name and detail:
        return clean_summary_text(f"{tool_name} 需要审批：{detail}", max_chars)
    if tool_name:
        return clean_summary_text(f"{tool_name} 需要审批", max_chars)
    return clean_summary_text(f"需要审批：{detail}", max_chars)


def extract_summary(runtime: str, event: str, payload: dict[str, Any], max_chars: int) -> str | None:
    if event == "completion":
        for candidate in (
            _extract_text(payload.get("last_assistant_message")),
            _extract_text(payload.get("lastAssistantMessage")),
            _extract_text(payload.get("content")),
            _extract_text(payload.get("message")),
            _extract_text(payload.get("summary")),
            _extract_text(payload.get("error")),
            *reversed(_read_transcript_messages(_extract_text(payload.get("transcript_path")))),
            *reversed(_read_transcript_messages(_extract_text(payload.get("transcriptPath")))),
        ):
            summary = clean_summary_text(candidate, max_chars)
            if summary:
                return summary
        return None

    if event == "approval_needed":
        tool_input = _extract_dict(payload.get("tool_input"))
        if not tool_input:
            tool_input = _extract_dict(payload.get("params"))
        require_approval = _extract_dict(payload.get("requireApproval"))
        approval = _extract_dict(payload.get("approval"))
        for candidate in (
            _extract_text(require_approval.get("description")),
            _extract_text(approval.get("description")),
            _extract_text(payload.get("description")),
            _extract_text(payload.get("title")),
        ):
            summary = clean_summary_text(candidate, max_chars)
            if summary:
                return summary
        description = clean_summary_text(_extract_text(tool_input.get("description")), max_chars)
        if description:
            return description
        tool_name = _extract_text(payload.get("tool_name") or payload.get("toolName"))
        detail = _safe_tool_detail(tool_input)
        summary = _approval_tool_summary(tool_name, detail, max_chars)
        if summary:
            return summary
        message = clean_summary_text(_extract_text(payload.get("message")), max_chars)
        if message:
            return message
        return None

    return None


def _normalized_payload_text(value: Any) -> str:
    return " ".join((_extract_text(value) or "").split()).strip()


def _is_no_reply_text(text: str | None) -> bool:
    return bool(text and text.strip().upper() == "NO_REPLY")


def _openclaw_payload_is_no_reply(payload: dict[str, Any], message: str | None) -> bool:
    if _is_no_reply_text(message):
        return True
    for key in ("content", "message", "summary", "last_assistant_message", "lastAssistantMessage"):
        if _is_no_reply_text(_normalized_payload_text(payload.get(key))):
            return True
    return False


def _openclaw_has_reply_context(payload: dict[str, Any], message: str | None) -> bool:
    if message and not _is_no_reply_text(message):
        return True
    for key in ("content", "message", "summary", "last_assistant_message", "lastAssistantMessage"):
        text = _normalized_payload_text(payload.get(key))
        if text and not _is_no_reply_text(text):
            return True
    for key in ("messageId", "message_id", "conversationId", "conversation_id", "channelId", "channel_id"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return True
    return False


def _openclaw_has_failure_context(payload: dict[str, Any]) -> bool:
    for key in ("error", "reason", "status", "failureReason", "failure_reason"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return True
        if isinstance(value, dict) and any(value.values()):
            return True
    for key in ("messageId", "message_id", "conversationId", "conversation_id", "channelId", "channel_id", "channel"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return True
    return False


def skip_notification_reason(runtime: str, event: str, payload: dict[str, Any], message: str | None) -> str | None:
    if runtime != "openclaw":
        return None
    if _openclaw_payload_is_no_reply(payload, message):
        return "skipped_openclaw_no_reply"

    hook_event = _hook_event_name(payload)
    if hook_event not in {"agent_end", "agent:end"}:
        return None
    if event == "completion" and not _openclaw_has_reply_context(payload, message):
        return "skipped_openclaw_silent_agent_end"
    if event == "failed" and not _openclaw_has_failure_context(payload):
        return "skipped_openclaw_silent_agent_end"
    return None


def build_dedupe_key(runtime: str, event: str, payload: dict[str, Any], body: str) -> str:
    session = payload.get("session_id") or payload.get("sessionId") or payload.get("sessionKey") or payload.get("conversation_id") or payload.get("transcript_path") or ""
    stable_payload = {
        "hook_event_name": payload.get("hook_event_name") or payload.get("event") or payload.get("event_name") or payload.get("type"),
        "session_id": session,
        "message_id": payload.get("messageId") or payload.get("message_id"),
        "conversation_id": payload.get("conversationId") or payload.get("conversation_id"),
        "tool_name": payload.get("tool_name") or payload.get("toolName"),
        "cwd": payload.get("cwd") or payload.get("workspaceDir"),
        "body": body,
    }
    digest = hashlib.sha256(json.dumps(stable_payload, sort_keys=True, ensure_ascii=False).encode()).hexdigest()[:16]
    return f"{runtime}:{event}:{session}:{digest}"


def _dedupe_dir(env: dict[str, str]) -> Path:
    base = _env_value(env, "AGENT_BARK_NOTIFY_STATE_DIR")
    if base:
        return Path(base)
    return Path(tempfile.gettempdir()) / "bark-agent-hook"


def already_sent(dedupe_key: str, env: dict[str, str], *, now: float | None = None) -> bool:
    now = now if now is not None else time.time()
    state_dir = _dedupe_dir(env)
    state_dir.mkdir(parents=True, exist_ok=True)
    for path in state_dir.iterdir():
        try:
            if now - path.stat().st_mtime > DEDUP_TTL_SECONDS:
                path.unlink()
        except OSError:
            continue
    path = state_dir / hashlib.sha256(dedupe_key.encode()).hexdigest()
    if path.exists():
        return True
    path.write_text(str(int(now)))
    return False


def build_notification(
    *,
    runtime: str,
    event: str,
    message: str | None,
    env: dict[str, str],
    payload: dict[str, Any],
    lody_settings: LodySettings,
    group_mode: GroupMode = "agent",
    cwd: Path | None = None,
) -> Notification | None:
    device_key = _env_value(env, "BARK_DEVICE_KEY")
    if not device_key:
        return None

    identity = identity_for_runtime(runtime, env, lody_settings)
    body = safe_message(event, message)
    title = notification_title(runtime=runtime, identity=identity, event=event, payload=payload, env=env, lody_settings=lody_settings, cwd=cwd)
    bark_server = _env_value(env, "BARK_SERVER", "https://api.day.app")
    dedupe_key = build_dedupe_key(runtime, event, payload, body)
    return Notification(
        title=title,
        body=body,
        icon_url=identity.icon_url,
        group=notification_group(identity=identity, payload=payload, env=env, group_mode=group_mode, cwd=cwd),
        bark_url=f"{bark_server.rstrip('/')}/{device_key}",
        click_url=hook_click_url(runtime=runtime, identity=identity, event=event, payload=payload, env=env, lody_settings=lody_settings, cwd=cwd),
        dedupe_key=dedupe_key,
    )


def send_bark(notification: Notification) -> None:
    data = {
        "title": notification.title,
        "body": notification.body,
        "icon": notification.icon_url,
    }
    if notification.group:
        data["group"] = notification.group
    if notification.click_url:
        data["url"] = notification.click_url
    with httpx.Client(timeout=10) as client:
        client.post(notification.bark_url, data=data).raise_for_status()


def _run_install_command(args: list[str], *, input_text: str | None = None) -> CommandResult:
    proc = subprocess.run(
        args,
        input=input_text,
        capture_output=True,
        text=True,
        check=False,
    )
    return CommandResult(args=args, returncode=proc.returncode, stdout=proc.stdout or "", stderr=proc.stderr or "")


def _run_required(args: list[str], *, input_text: str | None = None) -> CommandResult:
    result = _run_install_command(args, input_text=input_text)
    if result.returncode != 0:
        raise RuntimeError(_command_failure_message(result))
    return result


def _run_required_idempotent(args: list[str], *, input_text: str | None = None) -> CommandResult:
    result = _run_install_command(args, input_text=input_text)
    if result.returncode == 0 or _looks_already_configured(result):
        return result
    raise RuntimeError(_command_failure_message(result))


def _looks_already_configured(result: CommandResult) -> bool:
    message = f"{result.stdout} {result.stderr}".lower()
    return "already" in message and any(word in message for word in ("exist", "configured", "installed", "enabled"))


def _command_failure_message(result: CommandResult) -> str:
    detail = " ".join((result.stderr or result.stdout).split())
    command = " ".join(result.args)
    if detail:
        return f"{command} exited {result.returncode}: {detail}"
    return f"{command} exited {result.returncode}"


def _json_from_command(args: list[str]) -> Any:
    result = _run_install_command(args)
    if result.returncode != 0:
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def _codex_installed_version() -> str | None:
    data = _json_from_command(["codex", "plugin", "list", "--json"])
    if not isinstance(data, dict):
        return None
    installed = data.get("installed")
    if not isinstance(installed, list):
        return None
    for item in installed:
        if not isinstance(item, dict):
            continue
        if item.get("pluginId") == "bark-agent-hook-codex@bark-agent-hook":
            version = item.get("version")
            return str(version) if version is not None else None
    return None


def _claude_installed_version() -> str | None:
    data = _json_from_command(["claude", "plugin", "list", "--json"])
    if not isinstance(data, list):
        return None
    for item in data:
        if not isinstance(item, dict):
            continue
        if item.get("id") == "bark-agent-hook@bark-agent-hook" and item.get("scope") == "user":
            version = item.get("version")
            return str(version) if version is not None else None
    return None


def _find_version(value: Any) -> str | None:
    if isinstance(value, dict):
        version = value.get("version")
        if version is not None and not isinstance(version, dict | list):
            return str(version)
        for item in value.values():
            found = _find_version(item)
            if found:
                return found
    if isinstance(value, list):
        for item in value:
            found = _find_version(item)
            if found:
                return found
    return None


def _openclaw_installed_version() -> str | None:
    data = _json_from_command(["openclaw", "plugins", "inspect", "bark-agent-hook-openclaw", "--runtime", "--json"])
    return _find_version(data)


def _parse_version_parts(version: str) -> list[int] | None:
    parts: list[int] = []
    for raw_part in version.split("."):
        if not raw_part.isdigit():
            return None
        parts.append(int(raw_part))
    return parts or None


def _version_change(before: str | None, after: str | None) -> InstallStatus:
    if before is None:
        return "installed"
    if after is None:
        return "updated"
    if before == after:
        return "unchanged"
    before_parts = _parse_version_parts(before)
    after_parts = _parse_version_parts(after)
    if before_parts is None or after_parts is None:
        return "updated"
    return "updated" if after_parts > before_parts else "downgraded"


def _uninstall_version_change(before: str | None, after: str | None) -> InstallStatus:
    if before is None:
        return "unchanged"
    if after is None:
        return "removed"
    return "unchanged"


def _version_text(before: str | None, after: str | None) -> str:
    before_text = before or "none"
    after_text = after or "unknown"
    if before is not None and after is not None and before == after:
        return after
    return f"{before_text} -> {after_text}"


def _openclaw_plugin_dir() -> Path:
    return Path(__file__).resolve().parents[1] / "plugins" / "bark-agent-hook-openclaw"


def _install_codex(cli_path: str) -> InstallResult:
    before = _codex_installed_version()
    try:
        _run_required_idempotent(["codex", "plugin", "marketplace", "add", "qsoyq/bark-agent-hook"])
        _run_required(["codex", "plugin", "marketplace", "upgrade", "bark-agent-hook"])
        _run_required_idempotent(["codex", "plugin", "add", "bark-agent-hook-codex@bark-agent-hook"])
    except RuntimeError as e:
        return InstallResult("Codex", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _codex_installed_version()
    status = _version_change(before, after)
    return InstallResult("Codex", status, before, after, cli_path, cli_path)


def _install_claude(cli_path: str) -> InstallResult:
    before = _claude_installed_version()
    try:
        _run_required_idempotent(["claude", "plugin", "marketplace", "add", "qsoyq/bark-agent-hook", "--scope", "user"])
        _run_required(["claude", "plugin", "marketplace", "update", "bark-agent-hook"])
        if before is None:
            _run_required(["claude", "plugin", "install", "bark-agent-hook@bark-agent-hook", "--scope", "user"])
        else:
            _run_required(["claude", "plugin", "update", "bark-agent-hook@bark-agent-hook", "--scope", "user"])
    except RuntimeError as e:
        return InstallResult("Claude Code", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _claude_installed_version()
    status = _version_change(before, after)
    return InstallResult("Claude Code", status, before, after, cli_path, cli_path)


def _install_openclaw(cli_path: str) -> InstallResult:
    before = _openclaw_installed_version()
    plugin_dir = _openclaw_plugin_dir()
    if not plugin_dir.is_dir():
        return InstallResult(
            "OpenClaw",
            "failed",
            before,
            None,
            cli_path,
            f"Missing local plugin directory: {plugin_dir}",
        )
    try:
        _run_required_idempotent(["openclaw", "plugins", "install", "--link", str(plugin_dir)])
        _run_required_idempotent(["openclaw", "plugins", "enable", "bark-agent-hook-openclaw"])
        _run_required(["openclaw", "config", "patch", "--stdin"], input_text=OPENCLAW_CONVERSATION_ACCESS_PATCH)
        _run_required(["openclaw", "gateway", "restart"])
    except RuntimeError as e:
        return InstallResult("OpenClaw", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _openclaw_installed_version()
    status = _version_change(before, after)
    return InstallResult("OpenClaw", status, before, after, cli_path, cli_path)


def _uninstall_codex(cli_path: str) -> InstallResult:
    before = _codex_installed_version()
    if before is None:
        return InstallResult("Codex", "unchanged", before, None, cli_path, "Plugin not installed")
    try:
        _run_required_idempotent(["codex", "plugin", "remove", "bark-agent-hook-codex@bark-agent-hook"])
    except RuntimeError as e:
        return InstallResult("Codex", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _codex_installed_version()
    status = _uninstall_version_change(before, after)
    note = cli_path if status == "removed" else "Plugin still appears installed"
    return InstallResult("Codex", status, before, after, cli_path, note)


def _uninstall_claude(cli_path: str) -> InstallResult:
    before = _claude_installed_version()
    if before is None:
        return InstallResult("Claude Code", "unchanged", before, None, cli_path, "Plugin not installed")
    try:
        _run_required_idempotent(["claude", "plugin", "uninstall", "bark-agent-hook@bark-agent-hook", "--scope", "user"])
    except RuntimeError as e:
        return InstallResult("Claude Code", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _claude_installed_version()
    status = _uninstall_version_change(before, after)
    note = cli_path if status == "removed" else "Plugin still appears installed"
    return InstallResult("Claude Code", status, before, after, cli_path, note)


def _openclaw_supports_plugins_command(command: str) -> bool:
    return _run_install_command(["openclaw", "plugins", command, "--help"]).returncode == 0


def _uninstall_openclaw(cli_path: str) -> InstallResult:
    before = _openclaw_installed_version()
    if before is None:
        return InstallResult("OpenClaw", "unchanged", before, None, cli_path, "Plugin not installed")
    remove_command: list[str] | None = None
    try:
        _run_required_idempotent(["openclaw", "plugins", "disable", "bark-agent-hook-openclaw"])
        if _openclaw_supports_plugins_command("remove"):
            remove_command = ["openclaw", "plugins", "remove", "bark-agent-hook-openclaw"]
        elif _openclaw_supports_plugins_command("uninstall"):
            remove_command = ["openclaw", "plugins", "uninstall", "bark-agent-hook-openclaw"]
        if remove_command is not None:
            _run_required_idempotent(remove_command)
        _run_required(["openclaw", "gateway", "restart"])
    except RuntimeError as e:
        return InstallResult("OpenClaw", "failed", before, None, cli_path, str(e), _extract_command_from_error(str(e)))
    after = _openclaw_installed_version()
    status = _uninstall_version_change(before, after)
    note = cli_path if status == "removed" else "Plugin disabled; remove command unavailable or inspect still reports it"
    return InstallResult("OpenClaw", status, before, after, cli_path, note)


def _extract_command_from_error(message: str) -> list[str] | None:
    command = message.split(" exited ", 1)[0].strip()
    return command.split() if command else None


def _selected_agent_values(agents: list[AgentOption] | None) -> set[str] | None:
    if not agents:
        return None
    return {agent.value for agent in agents}


def _run_for_available_agents(agents: list[AgentOption] | None, actions: list[tuple[str, str, Any]]) -> list[InstallResult]:
    selected = _selected_agent_values(agents)
    results: list[InstallResult] = []
    for agent, command, action in actions:
        if selected is not None and command not in selected:
            continue
        cli_path = shutil.which(command)
        if cli_path is None:
            results.append(InstallResult(agent, "skipped", None, None, None, "CLI not found"))
            continue
        results.append(action(cli_path))
    return results


def _install_for_available_agents(agents: list[AgentOption] | None = None) -> list[InstallResult]:
    return _run_for_available_agents(
        agents,
        [
            ("Codex", "codex", _install_codex),
            ("Claude Code", "claude", _install_claude),
            ("OpenClaw", "openclaw", _install_openclaw),
        ],
    )


def _uninstall_for_available_agents(agents: list[AgentOption] | None = None) -> list[InstallResult]:
    return _run_for_available_agents(
        agents,
        [
            ("Codex", "codex", _uninstall_codex),
            ("Claude Code", "claude", _uninstall_claude),
            ("OpenClaw", "openclaw", _uninstall_openclaw),
        ],
    )


def _status_style(status: InstallStatus) -> str:
    return {
        "installed": "green",
        "updated": "cyan",
        "downgraded": "yellow",
        "unchanged": "blue",
        "removed": "green",
        "failed": "red",
        "skipped": "dim",
    }[status]


def _succeeded(results: list[InstallResult]) -> int:
    return sum(1 for result in results if result.status in {"installed", "updated", "downgraded", "unchanged", "removed"})


def _skipped(results: list[InstallResult]) -> int:
    return sum(1 for result in results if result.status == "skipped")


def _failed(results: list[InstallResult]) -> int:
    return sum(1 for result in results if result.status == "failed")


def _found_cli_count(results: list[InstallResult]) -> int:
    return sum(1 for result in results if result.status != "skipped")


def _print_action_results(results: list[InstallResult], console: Console, *, title: str) -> None:
    console.print(f"[bold]{title}[/bold]")
    console.print()
    table = Table()
    table.add_column("Agent")
    table.add_column("Status")
    table.add_column("Version")
    table.add_column("CLI / Notes")
    for result in results:
        note = result.note
        if result.status in {"installed", "updated", "downgraded", "unchanged", "removed"} and result.cli_path and result.note == result.cli_path:
            note = result.cli_path
        table.add_row(
            result.agent,
            f"[{_status_style(result.status)}]{result.status}[/{_status_style(result.status)}]",
            _version_text(result.before_version, result.after_version) if result.status != "skipped" else "-",
            note,
        )
    console.print(table)
    console.print()
    console.print(f"Summary: {_succeeded(results)} succeeded, {_skipped(results)} skipped, {_failed(results)} failed.")
    if _found_cli_count(results) == 0:
        console.print("No plugin action was attempted because no supported agent CLI was found.")
    failed_results = [result for result in results if result.status == "failed"]
    if failed_results:
        console.print()
        console.print("[red]Failed agents:[/red]")
        for result in failed_results:
            command = " ".join(result.failed_command or [])
            detail = command or result.note
            console.print(f"  {result.agent}: {detail}")


def _print_install_results(results: list[InstallResult], console: Console) -> None:
    _print_action_results(results, console, title="Bark Agent Hook install")
    console.print()
    _print_install_next_steps(results, console)


def _print_uninstall_results(results: list[InstallResult], console: Console) -> None:
    _print_action_results(results, console, title="Bark Agent Hook uninstall")
    console.print()
    console.print("Marketplace sources, environment variables, and historical audit logs were left unchanged.")


def _print_install_next_steps(results: list[InstallResult], console: Console) -> None:
    if _found_cli_count(results) == 0:
        console.print("[bold]Next steps:[/bold]")
        console.print("  Install Codex, Claude Code, or OpenClaw first, then run:")
        console.print("  bark-agent-hook install")
        console.print()
        console.print("  Set BARK_DEVICE_KEY=<your Bark device key> before testing notifications.")
        return
    console.print("[bold]Next steps:[/bold]")
    console.print("  Set BARK_DEVICE_KEY=<your Bark device key>")
    console.print("  Optional: BARK_SERVER=https://api.day.app")
    console.print("  Optional: BARK_GROUP=<fixed Bark group>")
    console.print("  Optional: AGENT_BARK_NOTIFY_GROUP_MODE=agent|project|project-branch")
    console.print("  Optional: AGENT_BARK_NOTIFY_HOOK_URL=  # empty by default; optional click URL template")
    console.print("  Example: AGENT_BARK_NOTIFY_HOOK_URL=https://lody.ai/users/{LODY_ELECTRON_SESSION_USER_ID}/sessions/{LODY_SESSION_ID}")
    console.print("  Optional: AGENT_BARK_NOTIFY_AUDIT_LOG=1")
    console.print("  Optional: AGENT_BARK_NOTIFY_AUDIT_LOG_FILE=~/.bark-agent-hook/bark-agent-hook.log")
    console.print()
    if any(result.agent == "Codex" for result in results):
        console.print()
        console.print("[bold]Codex note:[/bold]")
        console.print("  If Codex runs hooks in a restricted shell/sandbox, set these variables in the environment inherited by Codex hook commands.")
    if any(result.agent == "OpenClaw" for result in results):
        console.print()
        console.print("[bold]OpenClaw note:[/bold]")
        console.print("  If OpenClaw Gateway runs as a service, set these variables in its wrapper/launchd/systemd/schtasks environment, then restart the gateway.")
    if any(result.agent == "OpenClaw" and result.status == "failed" and "Missing local plugin directory" in result.note for result in results):
        console.print()
        console.print("OpenClaw install currently requires the local plugin directory from the bark-agent-hook source checkout.")
        console.print("Run from the source checkout, or add packaged/remote OpenClaw plugin support in a follow-up.")


@cmd.command()
def install(
    agents: list[AgentOption] | None = typer.Option(None, "--agent", help="Agent plugin to install. Repeat for multiple agents. Defaults to all supported agents."),
) -> None:
    """Install bark-agent-hook plugins for locally available agents.

    This command checks for codex, claude, and openclaw CLIs in PATH unless
    one or more --agent options are passed. Missing CLIs are skipped.

    Installed plugins:
      Codex:        bark-agent-hook-codex@bark-agent-hook
      Claude Code:  bark-agent-hook@bark-agent-hook --scope user
      OpenClaw:     local linked plugin from plugins/bark-agent-hook-openclaw
    """
    results = _install_for_available_agents(agents)
    _print_install_results(results, Console(highlight=False, width=120))
    if _found_cli_count(results) > 0 and _succeeded(results) == 0:
        raise typer.Exit(1)


@cmd.command()
def uninstall(
    agents: list[AgentOption] | None = typer.Option(None, "--agent", help="Agent plugin to uninstall. Repeat for multiple agents. Defaults to all supported agents."),
) -> None:
    """Uninstall bark-agent-hook plugins for locally available agents."""
    results = _uninstall_for_available_agents(agents)
    _print_uninstall_results(results, Console(highlight=False, width=120))
    if _found_cli_count(results) > 0 and _succeeded(results) == 0:
        raise typer.Exit(1)


@cmd.command()
def hook(
    runtime: Runtime = typer.Option("auto", "--runtime", help="Hook runtime: codex, claude, openclaw, or auto."),
    event: Event = typer.Option("auto", "--event", help="Notification event override."),
    message: str | None = typer.Option(None, "--message", help="Override short notification body."),
    group_mode: GroupModeOption | None = typer.Option(None, "--group-mode", help="Bark group mode: agent, project, or project-branch."),
    summary_mode: SummaryMode = typer.Option("fixed", "--summary-mode", help="Notification summary mode: fixed or extract."),
    summary_max_chars: int = typer.Option(DEFAULT_SUMMARY_MAX_CHARS, "--summary-max-chars", min=1, help="Maximum extractive summary length."),
    dry_run: bool = typer.Option(False, "--dry-run", help="Print notification summary without sending Bark request."),
    no_dedupe: bool = typer.Option(False, "--no-dedupe", help="Disable duplicate suppression."),
) -> None:
    """Read hook JSON from stdin and send a best-effort Bark notification."""
    env = dict(os.environ)
    payload = parse_hook_payload(_read_stdin())
    lody_settings = LodySettings()
    resolved_runtime = detect_runtime(runtime, env, payload, lody_settings)
    resolved_event = detect_event(event, payload)
    resolved_group_mode = resolve_group_mode(group_mode, env)
    audit_record = _new_audit_record(runtime=resolved_runtime, event=resolved_event, payload=payload, summary_mode=summary_mode, lody_settings=lody_settings)
    try:
        if resolved_event is None:
            _finish_audit_record(env, audit_record, status="skipped_unsupported_event")
            if dry_run:
                typer.echo("skip: unsupported hook event")
            return

        resolved_message = message
        if resolved_message is None and summary_mode == "extract":
            resolved_message = extract_summary(resolved_runtime, resolved_event, payload, summary_max_chars)

        skip_reason = skip_notification_reason(resolved_runtime, resolved_event, payload, resolved_message)
        if skip_reason is not None:
            _finish_audit_record(env, audit_record, status=skip_reason)
            if dry_run:
                typer.echo("skip: OpenClaw event has no deliverable reply")
            return

        notification = build_notification(
            runtime=resolved_runtime,
            event=resolved_event,
            message=resolved_message,
            env=env,
            payload=payload,
            lody_settings=lody_settings,
            group_mode=resolved_group_mode,
        )
        if notification is None:
            _finish_audit_record(env, audit_record, status="skipped_missing_device_key")
            if dry_run:
                typer.echo("skip: BARK_DEVICE_KEY is missing")
            return

        if not no_dedupe and already_sent(notification.dedupe_key, env):
            _finish_audit_record(env, audit_record, status="skipped_duplicate", notification=notification)
            if dry_run:
                typer.echo("skip: duplicate notification")
            return

        if dry_run:
            _finish_audit_record(env, audit_record, status="sent", notification=notification)
            output = {"title": notification.title, "body": notification.body, "icon": notification.icon_url, "group": notification.group, "url": notification.bark_url}
            if notification.click_url:
                output["click_url"] = notification.click_url
            typer.echo(json.dumps(output, ensure_ascii=False))
            return

        try:
            send_bark(notification)
        except httpx.HTTPError as e:
            _finish_audit_record(env, audit_record, status="bark_http_error", notification=notification, error=e)
            typer.echo(f"Bark notification failed: {e}", err=True)
            return
        _finish_audit_record(env, audit_record, status="sent", notification=notification)
    except Exception as e:
        _finish_audit_record(env, audit_record, status="hook_exception", error=e)
        typer.echo(f"Bark hook failed: {e}", err=True)
        return


if __name__ == "__main__":
    cmd()
